INSERT INTO crust_type(name)
VALUES ('Aucune'),
       ('Fleurie'),
       ('Naturelle'),
       ('Lavée'),
       ('Sèche'),
       ('Cirée');

INSERT INTO dough_type(name)
VALUES ('Molle'),
       ('Pressée non cuite'),
       ('Pressée cuite'),
       ('Persillée'),
       ('Frais'),
       ('Fondue'),
       ('Filée'),
       ('Lactique');

INSERT INTO milk_type(name)
VALUES ('Vache'),
       ('Chèvre'),
       ('Brebis'),
       ('Vache & Brebis'),
       ('Vache & Chèvre'),
       ('Chèvre & Brebis');

INSERT INTO cheese(name, slug, aoc_year, aop_year, igp_year, dough_type_id, crust_type_id, milk_type_id)
VALUES ('Abbaye de la Pierre-qui-Vire', 'abbaye-de-la-pierre-qui-vire', null, null, null, 1, 4, 1),
       ('Bleu d''Auvergne', 'bleu-d-auvergne', 1975, 1996, null, 4, 1, 1),
       ('Anneau du Vic-Bilh', 'anneau-du-vic-bilh', 2023, null, null, 1, 3, 2),
       ('Angors', 'angors', null, null, null, 1, 3, 2),
       ('Abondance', 'abondance', null, 1990, null, 3, 1, 1),
       ('Beaufort', 'beaufort', null, 1968, null, 3, 1, 1),
       ('Appenzeller', 'appenzeller', null, null, null, 3, 1, 1),
       ('Besace Fermière', 'besace-fermiere', null, null, null, 1, 3, 2),
       ('Bethmale', 'bethmale', null, null, null, 2, 1, 1),
       ('Bergues Torchon', 'bergues-torchon', null, null, null, 1, 4, 1),
       ('Bichonnet', 'bichonnet', null, null, null, 1, 3, 2),
       ('Bleu de Planèze', 'bleu-de-planeze', null, null, null, 4, 1, 1),
       ('Bleu de Bonneval', 'bleu-de-bonneval', null, null, null, 4, 1, 1),
       ('Bleu de Gex', 'bleu-de-gex', 1977, 2008, null, 4, 1, 1),
       ('Bleu du Vercors-Sassenage', 'bleu-du-vercors-sassenage', null, null, null, 4, 1, 1),
       ('Bleu de la Chataigneraie', 'bleu-de-la-chataigneraie', null, null, null, 4, 1, 1),
       ('Bleu du Val d''Aillon', 'bleu-du-val-d-aillon', null, null, null, 4, 1, 1),
       ('Bouquetou du Vernet', 'bouquetou-du-vernet', null, null, null, 1, 3, 2),
       ('Bleu fermier de Haute', 'bleu-fermier-de-haute', null, null, null, 4, 1, 1),
       ('Bleu des Causses', 'bleu-des-causses', 1979, 1996, null, 4, 1, 1),
       ('Bleu de laqueuille', 'bleu-de-laqueuille', null, null, null, 4, 1, 1),
       ('Boulette d''avesnes', 'boulette-d-avesnes', null, null, null, 1, 4, 1),
       ('Bouton de culotte', 'bouton-de-culotte', null, null, null, 1, 3, 2),
       ('Brie de Melun', 'brie-de-melun', 1980, 1996, null, 1, 2, 1),
       ('Brézain', 'brezain', null, null, null, 2, 1, 1),
       ('Brie de Meaux', 'brie-de-meaux', 1980, 1996, null, 1, 2, 1),
       ('Bouyguette de chèvre', 'bouyguette-de-chevre', null, null, null, 1, 3, 2),
       ('Brie de Brebis', 'brie-de-brebis', null, null, null, 1, 2, 3),
       ('Brillat-Savarin', 'brillat-savarin', null, null, 2017, 1, 2, 1),
       ('Fleur du Maquis Corse', 'fleur-du-maquis-corse', null, null, null, 1, 3, 3),
       ('Brie de Nangis', 'brie-de-nangis', null, null, null, 1, 2, 1),
       ('Briquette de Cocumont', 'briquette-de-cocumont', null, null, null, 1, 3, 2),
       ('Briquette', 'briquette', null, null, null, 1, 2, 1),
       ('Briquette de brebis', 'briquette-de-brebis', null, null, null, 1, 3, 3),
       ('Buchette blanche ou cendrée', 'buchette-blanche-ou-cendree', null, null, null, 1, 3, 2),
       ('Carré du Vinage', 'carre-du-vinage', null, null, null, 1, 4, 1),
       ('Cabécou', 'cabecou', 1988, 1996, null, 1, 3, 2),
       ('Buronnier de l''Aubrac', 'buronnier-de-l-aubrac', null, null, 2023, 2, 1, 1),
       ('Camembert de Normandie', 'camembert-de-normandie', 1983, 1992, null, 1, 2, 1),
       ('Cabri Sel Fou', 'cabri-sel-fou', null, null, null, 1, 3, 2),
       ('Cantal', 'cantal', 1956, 1996, null, 2, 1, 1),
       ('Chabis blanc ou cendré', 'chabis-blanc-ou-cendre', null, null, null, 1, 3, 2),
       ('Charolais', 'charolais', 2010, 2014, null, 1, 3, 2),
       ('Chaource', 'chaource', 1970, 1996, null, 1, 2, 1),
       ('Chevrotin', 'chevrotin', 2002, 2005, null, 2, 1, 2),
       ('Chèvre cendré de Cocumont', 'chevre-cendre-de-cocumont', null, null, null, 1, 3, 2),
       ('Chevrillon', 'chevrillon', null, null, null, 1, 3, 2),
       ('Compostelle', 'compostelle', null, null, null, 1, 3, 2),
       ('Coeur cendré', 'coeur-cendre', null, null, null, 1, 3, 2),
       ('Cœur de chèvre', 'coeur-de-chevre', null, null, null, 1, 3, 2),
       ('Cœur de Savoie', 'coeur-de-savoie', null, null, null, 2, 1, 1),
       ('Colombier des Aillons', 'colombier-des-aillons', null, null, null, 2, 1, 1),
       ('Couronne des 4 Montagnes', 'couronne-des-4-montagnes', null, null, null, 1, 3, 1),
       ('Cosne du Morvan', 'cosne-du-morvan', null, null, null, 1, 3, 2),
       ('Comté', 'comte', 1958, 1996, null, 3, 1, 1),
       ('Crott ''Indre', 'crott-indre', null, null, null, 1, 3, 2),
       ('Couronne lochoise', 'couronne-lochoise', null, null, null, 1, 3, 2),
       ('Crémeux du Jura', 'cremeux-du-jura', null, null, null, 1, 4, 1),
       ('Coulommiers', 'coulommiers', null, null, null, 1, 2, 1),
       ('Crémeux d''Ossau', 'cremeux-d-ossau', null, null, null, 2, 1, 1),
       ('Crottin au poivre', 'crottin-au-poivre', null, null, null, 1, 3, 2),
       ('Crottin cendré', 'crottin-cendre', null, null, null, 1, 3, 2),
       ('Crottin de Chavignol', 'crottin-de-chavignol', 1976, 1996, null, 1, 3, 2),
       ('Curé Nantais', 'cure-nantais', null, null, null, 1, 4, 1),
       ('Crottin villageois fermier', 'crottin-villageois-fermier', null, null, null, 1, 3, 2),
       ('Doux chêne', 'doux-chene', null, null, null, 1, 2, 2),
       ('Crottin du Viornay', 'crottin-du-viornay', null, null, null, 1, 3, 2),
       ('Crottin de Cocumont', 'crottin-de-cocumont', null, null, null, 1, 3, 2),
       ('Elgines', 'elgines', null, null, null, 1, 3, 2),
       ('Emmental', 'emmental', null, null, null, 1, 4, 1),
       ('Epoisses', 'epoisses', 1991, 1996, null, 1, 4, 1),
       ('Etivaz', 'etivaz', null, null, null, 3, 1, 1),
       ('Fiore di muntagna', 'fiore-di-muntagna', null, null, null, 1, 4, 3),
       ('Fleur des Alpes', 'fleur-des-alpes', null, null, null, 3, 1, 1),
       ('Feuille du Limousin', 'feuille-du-limousin', null, null, null, 1, 3, 2),
       ('Fleur d''Aunis', 'fleur-d-aunis', null, null, null, 1, 4, 1),
       ('Fontina d''alpage', 'fontina-d-alpage', null, null, null, 2, 1, 1),
       ('Fourme d''Ambert', 'fourme-d-ambert', 1972, 1996, null, 4, 1, 1),
       ('Fourme fermière Valcivières', 'fourme-fermiere-valcivieres', null, null, null, 4, 1, 1),
       ('Flocon de Savoie', 'flocon-de-savoie', null, null, null, 1, 2, 1),
       ('Fourme de Montbrison', 'fourme-de-montbrison', 1972, 1996, null, 4, 1, 1),
       ('Fournols', 'fournols', null, null, null, 1, 4, 1),
       ('Fusette blanche', 'fusette-blanche', null, null, null, 1, 3, 2),
       ('Galet au Fenugrec', 'galet-au-fenugrec', null, null, null, 1, 3, 2),
       ('Gaperon', 'gaperon', null, null, null, 1, 3, 1),
       ('Galet de la Loire', 'galet-de-la-loire', null, null, null, 1, 1, 1),
       ('Gorgonzola', 'gorgonzola', null, null, null, 4, 1, 1),
       ('Galletout', 'galletout', null, null, null, 1, 3, 2),
       ('Gouda', 'gouda', null, null, null, 2, 1, 1),
       ('Galet boisé', 'galet-boise', null, null, null, 1, 2, 1),
       ('Grand Carré', 'grand-carre', null, null, null, 3, 1, 1),
       ('Gruyère Suisse d''Alpage', 'gruyere-suisse-d-alpage', null, null, null, 3, 1, 1),
       ('Jolirond', 'jolirond', null, null, null, 1, 2, 1),
       ('Kalaka', 'kalaka', null, null, null, 2, 1, 1),
       ('Gruyère français', 'gruyere-francais', null, null, null, 3, 1, 1),
       ('Kaltbach', 'kaltbach', null, null, null, 2, 1, 1),
       ('Banon', 'banon', 2003, 2007, null, 1, 2, 2),
       ('Laguiole', 'laguiole', 1961, 1996, null, 2, 1, 1),
       ('Langres', 'langres', 1991, 1996, null, 1, 4, 1),
       ('Lorenthym', 'lorenthym', null, null, null, 1, 3, 2),
       ('Livarot', 'livarot', 1975, 1996, null, 1, 4, 1),
       ('Lingot du berger', 'lingot-du-berger', null, null, null, 1, 3, 2),
       ('Maroilles', 'maroilles', null, null, null, 1, 4, 1),
       ('Luzenac', 'luzenac', null, null, null, 2, 1, 1),
       ('Manchego', 'manchego', null, null, null, 2, 1, 3),
       ('Magoth', 'magoth', null, null, null, 3, 1, 1),
       ('Mascaré', 'mascare', null, null, null, 1, 3, 2),
       ('Mimolette', 'mimolette', null, null, null, 2, 1, 1),
       ('Massadel fermier', 'massadel-fermier', null, null, null, 2, 1, 1),
       ('Mizotte', 'mizotte', null, null, null, 1, 4, 1),
       ('Mascarpone', 'mascarpone', null, null, null, 5, 1, 1),
       ('Mont d''Or', 'mont-d-or', 1981, 1996, null, 1, 4, 1),
       ('Moelleux du Revard', 'moelleux-du-revard', null, null, null, 1, 4, 1),
       ('Morbier', 'morbier', 2000, 2002, null, 2, 1, 1),
       ('Moulis de Vache', 'moulis-de-vache', null, null, null, 2, 1, 1),
       ('Mothais sur feuille', 'mothais-sur-feuille', null, null, null, 1, 3, 2),
       ('Mont-Jura', 'mont-jura', null, null, null, 3, 1, 1),
       ('Mozzarella di Bufala', 'mozzarella-di-bufala', null, null, null, 8, 1, 1),
       ('Munster-Géromé', 'munster-gerome', 1969, 1996, null, 1, 4, 1),
       ('Mâconnais', 'maconnais', 2006, 2010, null, 1, 2, 2),
       ('Ovalie Romarin', 'ovalie-romarin', null, null, null, 1, 3, 2),
       ('Olivet cendré', 'olivet-cendre', null, null, null, 1, 3, 1),
       ('Neufchâtel', 'neufchatel', 1969, 1996, null, 1, 2, 1),
       ('Palet cendré', 'palet-cendre', null, null, null, 1, 3, 2),
       ('Pardou', 'pardou', null, null, null, 2, 1, 4),
       ('Ossau-Iraty', 'ossau-iraty', 1980, 1996, null, 2, 1, 3),
       ('Parmigiano reggiano', 'parmigiano-reggiano', null, null, null, 3, 1, 1),
       ('Parthenay cendré', 'parthenay-cendre', null, null, null, 1, 3, 2),
       ('Pavé cendré', 'pave-cendre', null, null, null, 1, 3, 2),
       ('Pavé des Cévennes', 'pave-des-cevennes', null, null, null, 1, 3, 3),
       ('Pavé Fermier', 'pave-fermier', null, null, null, 1, 2, 1),
       ('Pavé du Larzac', 'pave-du-larzac', null, null, null, 1, 2, 3),
       ('Pavin', 'pavin', null, null, null, 2, 1, 1),
       ('Pecorino Stagionato', 'pecorino-stagionato', null, null, null, 3, 1, 3),
       ('Pélardon', 'pelardon', 2000, 2001, null, 1, 3, 2),
       ('Péraldou', 'peraldou', null, null, null, 1, 3, 3),
       ('Pérail de Brebis', 'perail-de-brebis', null, null, null, 1, 3, 3),
       ('Petit Louvie', 'petit-louvie', null, null, null, 1, 3, 2),
       ('Persillé de Tignes', 'persille-de-tignes', null, null, null, 2, 1, 5),
       ('Persillé de Chèvre', 'persille-de-chevre', null, null, null, 4, 1, 2),
       ('Petit Gaugry', 'petit-gaugry', null, null, null, 1, 4, 1),
       ('Petit Dongé', 'petit-donge', null, null, null, 1, 2, 1),
       ('Plaisir au Chablis', 'plaisir-au-chablis', null, null, null, 1, 4, 1),
       ('Petit Saint Point', 'petit-saint-point', null, null, null, 1, 4, 1),
       ('Picodon', 'picodon', 1983, 1996, null, 1, 3, 2),
       ('Pitchou', 'pitchou', null, null, null, 1, 3, 2),
       ('Pouligny-Saint-Pierre', 'pouligny-saint-pierre', 1972, 1996, null, 1, 3, 2),
       ('Pont l''Évêque', 'pont-l-eveque', 1972, 1996, null, 1, 4, 1),
       ('Pomerol', 'pomerol', null, null, null, 2, 1, 1),
       ('Rigotte de Condrieu', 'rigotte-de-condrieu', 2009, 2013, null, 1, 2, 1),
       ('Raclette', 'raclette', null, null, null, 2, 1, 1),
       ('Pyramide fermière', 'pyramide-fermiere', null, null, null, 1, 3, 2),
       ('Reblochon', 'reblochon', 1958, 1996, null, 2, 1, 1),
       ('Rocamadour', 'rocamadour', 1996, 1999, null, 1, 3, 2),
       ('Roquefort', 'roquefort', 1925, 1996, null, 4, 1, 3),
       ('Rovethym', 'rovethym', null, null, null, 1, 2, 2),
       ('Rove fermier', 'rove-fermier', null, null, null, 5, 1, 2),
       ('Sablé de Wissant', 'sable-de-wissant', null, null, null, 1, 4, 1),
       ('Saint-Félicien', 'saint-felicien', null, null, null, 1, 2, 1),
       ('Saint-Marcellin', 'saint-marcellin', null, null, null, 1, 3, 1),
       ('Saint-Jacques', 'saint-jacques', null, null, null, 1, 2, 1),
       ('Saulzais', 'saulzais', null, null, null, 1, 3, 3),
       ('Saint-Nectaire', 'saint-nectaire', 1955, 1996, null, 2, 1, 1),
       ('Saint-Paulin', 'saint-paulin', null, null, null, 2, 1, 1),
       ('Sainte-Maure de Touraine', 'sainte-maure-de-touraine', 1990, 1996, null, 1, 3, 2),
       ('Salers', 'salers', 1979, 1996, null, 2, 1, 1),
       ('Sauvaget', 'sauvaget', null, null, null, 1, 3, 2),
       ('Satonnay Pétales Roses', 'satonnay-petales-roses', null, null, null, 1, 3, 2),
       ('Selles-sur-Cher', 'selles-sur-cher', 1975, 1996, null, 1, 2, 2),
       ('Souréliette', 'soureliette', null, null, null, 2, 1, 3),
       ('Tête de Moine', 'tete-de-moine', null, null, null, 2, 1, 1),
       ('Soumaintrain', 'soumaintrain', null, null, null, 1, 4, 1),
       ('Stilton bleu', 'stilton-bleu', null, null, null, 4, 1, 1),
       ('Taleggio', 'taleggio', null, null, null, 1, 4, 1),
       ('Taupinière', 'taupiniere', null, null, null, 1, 3, 2),
       ('Tome des Bauges', 'tome-des-bauges', 2002, 2007, null, 2, 1, 1),
       ('Tomme du Cruzille', 'tomme-du-cruzille', null, null, null, 2, 1, 2),
       ('Tomme le Saulnois aux cones de Houblon', 'tomme-le-saulnois-aux-cones-de-houblon', null, null, null, 2, 1, 1),
       ('Tommette de brebis Etchegoinia', 'tommette-de-brebis-etchegoinia', null, null, null, 2, 1, 3),
       ('Tomme du Ségala', 'tomme-du-segala', null, null, null, 2, 1, 1),
       ('Tomme Ail des ours', 'tomme-ail-des-ours', null, null, null, 2, 1, 1),
       ('Tomme au chniu', 'tomme-au-chniu', null, null, null, 2, 1, 1),
       ('Tomme crayeuse fermière', 'tomme-crayeuse-fermiere', null, null, null, 2, 1, 1),
       ('Tomme d''Anjou', 'tomme-d-anjou', null, null, null, 2, 1, 1),
       ('Tomme brossée à la bière', 'tomme-brossee-a-la-biere', null, null, null, 2, 1, 1),
       ('Tomme au foin', 'tomme-au-foin', null, null, null, 2, 1, 1),
       ('Tomme de Montagne Dent du Chat', 'tomme-de-montagne-dent-du-chat', null, null, null, 2, 1, 1),
       ('Tomme de Montagne', 'tomme-de-montagne', null, null, null, 2, 1, 1),
       ('Tomme de Rilhac Xaintrie', 'tomme-de-rilhac-xaintrie', null, null, null, 2, 1, 1),
       ('Tomme de Montagne du Jura Suisse', 'tomme-de-montagne-du-jura-suisse', null, null, null, 3, 1, 1),
       ('Tomme de Rhuys', 'tomme-de-rhuys', null, null, null, 2, 1, 1),
       ('Tomme de Yenne', 'tomme-de-yenne', null, null, null, 2, 1, 1),
       ('Tomme de Savoie', 'tomme-de-savoie', null, null, null, 2, 1, 1),
       ('Tomme des Allobroges', 'tomme-des-allobroges', null, null, null, 2, 1, 1),
       ('Tomme du Limousin', 'tomme-du-limousin', null, null, null, 2, 1, 1),
       ('Tomme Piémontaise', 'tomme-piemontaise', null, null, null, 2, 1, 1),
       ('Tomme du Berry demi-vieille', 'tomme-du-berry-demi-vieille', null, null, null, 2, 1, 1),
       ('Tomme du Jura', 'tomme-du-jura', null, null, null, 2, 1, 1),
       ('Tommette bleue de Brebis', 'tommette-bleue-de-brebis', null, null, null, 4, 1, 3),
       ('Tommette de Chèvre de Savoie', 'tommette-de-chevre-de-savoie', null, null, null, 2, 1, 2),
       ('Tommette de Missilier', 'tommette-de-missilier', null, null, null, 2, 1, 1),
       ('Tomyère', 'tomyere', null, null, null, 3, 1, 1),
       ('Tourret', 'tourret', null, null, null, 1, 3, 2),
       ('Vacherin des Bauges', 'vacherin-des-bauges', null, null, null, 1, 4, 1),
       ('Tricorne', 'tricorne', null, null, null, 1, 3, 2),
       ('Vacherin Vaudois', 'vacherin-vaudois', null, null, null, 1, 4, 1),
       ('Vacherin', 'vacherin', null, null, null, 2, 1, 1),
       ('Vacherin Mont d''Or', 'vacherin-mont-d-or', null, null, null, 1, 4, 1),
       ('Brocciu', 'brocciu', 1998, 2003, null, 8, 1, 6),
       ('Vieux Lille', 'vieux-lille', null, null, null, 1, 4, 1),
       ('Valençay', 'valencay', 1998, 2004, null, 1, 3, 2),
       ('Chabichou du Poitou', 'chabichou-du-poitou', 1990, 1996, null, 1, 2, 2),
       ('La Brousse du Rove', 'la-brousse-du-rove', 2018, 2020, null, 5, 1, 2);